### ISSUE TITLE
token issue

### ISSUE THREAD

**Issue by AtharwaRanjan** [Z-Dux/Crused-Autocatcher#1]
how and where to place the token?

**Comment by AtharwaRanjan** [comment]
done! now?

**Comment by AtharwaRanjan** [comment]
> Add tokens.txt file

in tokens.txt how should i paste the token? with these "" or without?

**Comment by AtharwaRanjan** [comment]
> Just add token in series no ""

ok. but after adding the token and hitting "save file", the npm show invalid webhook url. why is it? do you have any idea?

**Comment by Pokamapapa** [comment]
> how and where to place the token?

Read the freaking instructions , everything is given there , just paste the plain token , no need of “ “ ,

**Comment by Pokamapapa** [comment]
> > Just add token in series no ""
> 
> ok. but after adding the token and hitting "save file", the npm show invalid webhook url. why is it? do you have any idea?

You have to copy the webhook url and paste it in captcha hook and webhook url , and save it
